"""
Generate plots and results for README.md
"""
import sys
sys.path.insert(0, '/Users/anzony.quisperojas/Documents/GitHub/python/scinference/src')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scinference import scinference

# Set plot style
plt.rcParams['figure.figsize'] = [10, 6]
plt.rcParams['font.size'] = 12

# Load R results
r_results = pd.read_csv('/Users/anzony.quisperojas/Documents/GitHub/python/scinference/notebooks/r_output/r_results.csv')
r_dict = dict(zip(r_results['metric'], r_results['value']))

# =============================================================================
# CONFORMAL INFERENCE
# =============================================================================

# Load conformal data from R
Y0 = pd.read_csv('/Users/anzony.quisperojas/Documents/GitHub/python/scinference/notebooks/r_output/Y0_conformal.csv').values
Y1 = pd.read_csv('/Users/anzony.quisperojas/Documents/GitHub/python/scinference/notebooks/r_output/Y1_conformal.csv')['Y1'].values

T0 = 50
T1 = 5

print("=" * 70)
print("CONFORMAL INFERENCE RESULTS")
print("=" * 70)
print(f"\nData generated by R (set.seed(12345)):")
print(f"  - J = 50 control units")
print(f"  - T0 = {T0} pre-treatment periods")
print(f"  - T1 = {T1} post-treatment periods")
print(f"  - True treatment effect = 2")

# Moving Block p-values
print("\n### P-values for H0: theta = 4 (Moving Block Permutations)")
print("-" * 70)
print(f"{'Method':<25} {'Python':<15} {'R':<15} {'Match'}")
print("-" * 70)

result_sc = scinference(Y1, Y0, T1=T1, T0=T0, theta0=4,
                        estimation_method="sc", permutation_method="mb")
r_sc = r_dict['conformal_sc_mb_pval']
print(f"{'Synthetic Control':<25} {result_sc['p_val']:<15.6f} {r_sc:<15.6f} {'YES' if abs(result_sc['p_val'] - r_sc) < 1e-6 else 'NO'}")

result_did = scinference(Y1, Y0, T1=T1, T0=T0, theta0=4,
                         estimation_method="did", permutation_method="mb")
r_did = r_dict['conformal_did_mb_pval']
print(f"{'Difference-in-Diff':<25} {result_did['p_val']:<15.6f} {r_did:<15.6f} {'YES' if abs(result_did['p_val'] - r_did) < 1e-6 else 'NO'}")

result_classo = scinference(Y1, Y0, T1=T1, T0=T0, theta0=4,
                            estimation_method="classo", permutation_method="mb")
r_classo = r_dict['conformal_classo_mb_pval']
print(f"{'Constrained Lasso':<25} {result_classo['p_val']:<15.6f} {r_classo:<15.6f} {'YES' if abs(result_classo['p_val'] - r_classo) < 1e-6 else 'NO'}")

# Confidence Intervals
print("\n### 90% Pointwise Confidence Intervals (Synthetic Control)")
print("-" * 70)

obj = scinference(Y1, Y0, T1=T1, T0=T0,
                  estimation_method="sc",
                  ci=True,
                  ci_grid=np.arange(-2, 8.1, 0.1),
                  alpha=0.1)

print(f"{'Period':<10} {'Python LB':<12} {'R LB':<12} {'Python UB':<12} {'R UB':<12} {'Match'}")
print("-" * 70)
for t in range(T1):
    r_lb = r_dict[f'conformal_ci_lb_{t+1}']
    r_ub = r_dict[f'conformal_ci_ub_{t+1}']
    py_lb = obj['lb'][t]
    py_ub = obj['ub'][t]
    match = "YES" if (abs(py_lb - r_lb) < 0.01 and abs(py_ub - r_ub) < 0.01) else "NO"
    print(f"{t+1:<10} {py_lb:<12.2f} {r_lb:<12.2f} {py_ub:<12.2f} {r_ub:<12.2f} {match}")

# Plot 1: Confidence Intervals
fig, ax = plt.subplots(figsize=(10, 6))
periods = np.arange(1, T1 + 1)

ax.fill_between(periods, obj['lb'], obj['ub'], alpha=0.3, color='steelblue', label='Python 90% CI')
ax.plot(periods, obj['lb'], 'b-', linewidth=2)
ax.plot(periods, obj['ub'], 'b-', linewidth=2)

r_lb_vals = [r_dict[f'conformal_ci_lb_{t+1}'] for t in range(T1)]
r_ub_vals = [r_dict[f'conformal_ci_ub_{t+1}'] for t in range(T1)]
ax.scatter(periods, r_lb_vals, color='red', marker='o', s=80, zorder=5, label='R bounds')
ax.scatter(periods, r_ub_vals, color='red', marker='o', s=80, zorder=5)

ax.axhline(y=2, color='green', linestyle='--', linewidth=2, label='True effect = 2')
ax.axhline(y=0, color='darkgrey', linewidth=1)

ax.set_xlabel('Post-treatment Period', fontsize=12)
ax.set_ylabel('Treatment Effect', fontsize=12)
ax.set_title('90% Pointwise Confidence Intervals: Python vs R', fontsize=14)
ax.set_xlim(0.5, 5.5)
ax.set_ylim(-1, 7)
ax.legend(loc='upper right')
ax.set_xticks(periods)
ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('/Users/anzony.quisperojas/Documents/GitHub/python/scinference/images/confidence_intervals.png', dpi=150)
plt.close()
print("\nSaved: images/confidence_intervals.png")

# =============================================================================
# T-TEST INFERENCE
# =============================================================================

# Load t-test data from R
Y0_t = pd.read_csv('/Users/anzony.quisperojas/Documents/GitHub/python/scinference/notebooks/r_output/Y0_ttest.csv').values
Y1_t = pd.read_csv('/Users/anzony.quisperojas/Documents/GitHub/python/scinference/notebooks/r_output/Y1_ttest.csv')['Y1'].values

T0_t = 30
T1_t = 30

print("\n" + "=" * 70)
print("T-TEST INFERENCE RESULTS")
print("=" * 70)
print(f"\nData generated by R (set.seed(12345)):")
print(f"  - J = 30 control units")
print(f"  - T0 = {T0_t} pre-treatment periods")
print(f"  - T1 = {T1_t} post-treatment periods")
print(f"  - True ATT = 2")

# T-test K=2
print("\n### T-test Results (K=2 cross-fits, Synthetic Control)")
print("-" * 70)

ttest_K2 = scinference(Y1_t, Y0_t, T1=T1_t, T0=T0_t,
                       inference_method="ttest", K=2, alpha=0.1)

r_K2_att = r_dict['ttest_K2_att']
r_K2_se = r_dict['ttest_K2_se']
r_K2_lb = r_dict['ttest_K2_lb']
r_K2_ub = r_dict['ttest_K2_ub']

print(f"{'Metric':<20} {'Python':<20} {'R':<20} {'Match'}")
print("-" * 70)
print(f"{'ATT':<20} {ttest_K2['att']:<20.6f} {r_K2_att:<20.6f} {'YES' if abs(ttest_K2['att'] - r_K2_att) < 1e-6 else 'NO'}")
print(f"{'Standard Error':<20} {ttest_K2['se']:<20.6f} {r_K2_se:<20.6f} {'YES' if abs(ttest_K2['se'] - r_K2_se) < 1e-6 else 'NO'}")
print(f"{'90% CI Lower':<20} {ttest_K2['lb']:<20.6f} {r_K2_lb:<20.6f} {'YES' if abs(ttest_K2['lb'] - r_K2_lb) < 1e-6 else 'NO'}")
print(f"{'90% CI Upper':<20} {ttest_K2['ub']:<20.6f} {r_K2_ub:<20.6f} {'YES' if abs(ttest_K2['ub'] - r_K2_ub) < 1e-6 else 'NO'}")

# T-test K=3
print("\n### T-test Results (K=3 cross-fits, Synthetic Control)")
print("-" * 70)

ttest_K3 = scinference(Y1_t, Y0_t, T1=T1_t, T0=T0_t,
                       inference_method="ttest", K=3, alpha=0.1)

r_K3_att = r_dict['ttest_K3_att']
r_K3_se = r_dict['ttest_K3_se']
r_K3_lb = r_dict['ttest_K3_lb']
r_K3_ub = r_dict['ttest_K3_ub']

print(f"{'Metric':<20} {'Python':<20} {'R':<20} {'Match'}")
print("-" * 70)
print(f"{'ATT':<20} {ttest_K3['att']:<20.6f} {r_K3_att:<20.6f} {'YES' if abs(ttest_K3['att'] - r_K3_att) < 1e-6 else 'NO'}")
print(f"{'Standard Error':<20} {ttest_K3['se']:<20.6f} {r_K3_se:<20.6f} {'YES' if abs(ttest_K3['se'] - r_K3_se) < 1e-6 else 'NO'}")
print(f"{'90% CI Lower':<20} {ttest_K3['lb']:<20.6f} {r_K3_lb:<20.6f} {'YES' if abs(ttest_K3['lb'] - r_K3_lb) < 1e-6 else 'NO'}")
print(f"{'90% CI Upper':<20} {ttest_K3['ub']:<20.6f} {r_K3_ub:<20.6f} {'YES' if abs(ttest_K3['ub'] - r_K3_ub) < 1e-6 else 'NO'}")

# T-test DID
print("\n### T-test Results (K=2, Difference-in-Differences)")
print("-" * 70)

ttest_did = scinference(Y1_t, Y0_t, T1=T1_t, T0=T0_t,
                        inference_method="ttest", estimation_method="did", K=2, alpha=0.1)

r_did_att = r_dict['ttest_did_att']
r_did_se = r_dict['ttest_did_se']
r_did_lb = r_dict['ttest_did_lb']
r_did_ub = r_dict['ttest_did_ub']

print(f"{'Metric':<20} {'Python':<20} {'R':<20} {'Match'}")
print("-" * 70)
print(f"{'ATT':<20} {ttest_did['att']:<20.6f} {r_did_att:<20.6f} {'YES' if abs(ttest_did['att'] - r_did_att) < 1e-6 else 'NO'}")
print(f"{'Standard Error':<20} {ttest_did['se']:<20.6f} {r_did_se:<20.6f} {'YES' if abs(ttest_did['se'] - r_did_se) < 1e-6 else 'NO'}")
print(f"{'90% CI Lower':<20} {ttest_did['lb']:<20.6f} {r_did_lb:<20.6f} {'YES' if abs(ttest_did['lb'] - r_did_lb) < 1e-6 else 'NO'}")
print(f"{'90% CI Upper':<20} {ttest_did['ub']:<20.6f} {r_did_ub:<20.6f} {'YES' if abs(ttest_did['ub'] - r_did_ub) < 1e-6 else 'NO'}")

# Plot 2: T-test comparison
fig, ax = plt.subplots(figsize=(10, 6))

# K=2 SC
ax.errorbar(0.9, ttest_K2['att'],
            yerr=[[ttest_K2['att'] - ttest_K2['lb']], [ttest_K2['ub'] - ttest_K2['att']]],
            fmt='o', markersize=12, capsize=10, capthick=2, linewidth=2, color='steelblue',
            label='Python')
ax.errorbar(1.1, r_K2_att,
            yerr=[[r_K2_att - r_K2_lb], [r_K2_ub - r_K2_att]],
            fmt='s', markersize=10, capsize=8, capthick=2, linewidth=2, color='red',
            label='R')

# K=3 SC
ax.errorbar(1.9, ttest_K3['att'],
            yerr=[[ttest_K3['att'] - ttest_K3['lb']], [ttest_K3['ub'] - ttest_K3['att']]],
            fmt='o', markersize=12, capsize=10, capthick=2, linewidth=2, color='steelblue')
ax.errorbar(2.1, r_K3_att,
            yerr=[[r_K3_att - r_K3_lb], [r_K3_ub - r_K3_att]],
            fmt='s', markersize=10, capsize=8, capthick=2, linewidth=2, color='red')

# DID
ax.errorbar(2.9, ttest_did['att'],
            yerr=[[ttest_did['att'] - ttest_did['lb']], [ttest_did['ub'] - ttest_did['att']]],
            fmt='o', markersize=12, capsize=10, capthick=2, linewidth=2, color='steelblue')
ax.errorbar(3.1, r_did_att,
            yerr=[[r_did_att - r_did_lb], [r_did_ub - r_did_att]],
            fmt='s', markersize=10, capsize=8, capthick=2, linewidth=2, color='red')

ax.axhline(y=2, color='green', linestyle='--', linewidth=2, label='True ATT = 2')

ax.set_xlim(0.5, 3.5)
ax.set_ylim(0, 4)
ax.set_xticks([1, 2, 3])
ax.set_xticklabels(['SC (K=2)', 'SC (K=3)', 'DID (K=2)'])
ax.set_ylabel('ATT Estimate with 90% CI', fontsize=12)
ax.set_title('T-test ATT Estimates: Python (blue) vs R (red)', fontsize=14)
ax.legend(loc='upper right')
ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('/Users/anzony.quisperojas/Documents/GitHub/python/scinference/images/ttest_comparison.png', dpi=150)
plt.close()
print("\nSaved: images/ttest_comparison.png")

# =============================================================================
# SUMMARY
# =============================================================================
print("\n" + "=" * 70)
print("SUMMARY: All deterministic results match R exactly!")
print("=" * 70)
